### ISSUE TITLE
/liblexbor_static.a: No such file or directory

### ISSUE THREAD

**Issue by nightmare-wolf** [CausticKirbyZ/SprayCannon#1] opened 2023-07-26 14:59 UTC
crystal build -p src/spraycannon.cr
cc: error: /root/Downloads/SprayCannon/lib/lexbor/src/lexbor/../ext/lexbor-c/build/liblexbor_static.a: No such file or directory
Error: execution of command failed with exit status 1: cc "${@}" -o /root/Downloads/SprayCannon/spraycannon  -rdynamic -L/usr/lib64/crystal /root/Downloads/SprayCannon/lib/lexbor/src/lexbor/../ext/lexbor-c/build/liblexbor_static.a -lxml2 -lz `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` -lsqlite3 -lpcre2-8 -lm -lgc -lpthread -levent   -lrt -lpthread -ldl

I am attempting to build this but i get an error stating that the lexbo_static.a file is missing. 

when i tried 
make init (worked fine)
make (nothing occurred and went to next line, assumed it worked)
make install (same error as above with the crystal build, states that file is missing and errors out).

I have crystal installed and dependencies satisfied. 
Please help.

**Comment by CausticKirbyZ** [comment] 2023-07-28 03:05
lexbor is a dependency used for html parsing and it has a post init process during the `shards install` process (make init). this should be where the liblexbor_static.a is built and is likely the cause of the failed build for spraycannon. 

If you `make clean` it should clean the shard dependancies(they download to the local lib/* folder) and allow you to start from scratch. 

i updated the Makefile in a recent build and a blank "make" wont do anything after make init. try `make all`  or `make spraycannon` to build.  the `make install` also depends on the 2 files being built (and thus will build them if they dont exist). ill update the readme shortly to reflect this change as well. 

if this still doesnt work try the following: 
- `make clean` - to clean the repo 
- `shards install` - install dependancies 
- `make spraycannon` 
- `make spdb` 
- `./spraycannon --version` - test to ensure the binary was build and runs
once it does you should be able to do `make install` to install it. 

I primarily use debian and arch based distros for testing builds, if you are using one that isn't in that group let me know and ill see if i can test it.

**Comment by nightmare-wolf** [comment] 2023-07-28 18:45
![image](https://github.com/CausticKirbyZ/SprayCannon/assets/41340083/5ebbb413-64da-488e-ad8e-2b0d8d4d4d2a)
I tried again with this method and i still get the same error.
I am actually running this on RHEL 7.

**Comment by CausticKirbyZ** [comment] 2023-07-28 19:12
I just went through this on a Kali install. The issue was that cmake wasnt installed. The lexbor post install process uses cmake. 

I will try to build a centos/rhel box at some point within the next week to check dependancies for this.

**Comment by nightmare-wolf** [comment] 2023-07-28 19:14
Awesome thanks.
Yes i did install cmake as i read online. But the issue still persisted.

**Comment by CausticKirbyZ** [comment] 2023-10-04 15:43
Looked into this several times and was ultimately not able to get it to compile on rhel7. Since static releases are now available, i am closing this as those should run on rhel7.

**Closed as completed by CausticKirbyZ** 2023-10-04 15:43 UTC
Labels: bug, RHEL7
